# -*- coding: utf-8 -*-
"""Major_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15uN6iec_J_aCcVknd0iZVQA2px-cuH88

Data Pre-proccessing

Data Segmentation
"""

import os
import csv
import shutil

# ===================== CONFIG =====================
BASE_PATH = "/content/drive/MyDrive"
DATASET_A_SRC = os.path.join(BASE_PATH, "/content/drive/MyDrive/Major_Project/Input_Dataset/Datasets_Deepfake")
DATASET_B_SRC = os.path.join(BASE_PATH, "/content/drive/MyDrive/Major_Project/Input_Dataset/FakeAVCeleb_v1.2")
OUTPUT_BASE = os.path.join(BASE_PATH, "/content/drive/MyDrive/Major_Project/Segmented_Dataset")

A_VIDEO_DIR = os.path.join(OUTPUT_BASE, "Dataset_A_video_only/videos")
B_VIDEO_DIR = os.path.join(OUTPUT_BASE, "Dataset_B_audio_visual/videos")

os.makedirs(A_VIDEO_DIR, exist_ok=True)
os.makedirs(B_VIDEO_DIR, exist_ok=True)

A_CSV = os.path.join(OUTPUT_BASE, "Dataset_A_video_only/dataset_A_index.csv")
B_CSV = os.path.join(OUTPUT_BASE, "Dataset_B_audio_visual/dataset_B_index.csv")

# ===================== CSV HEADERS =====================
a_rows = [["video_id", "video_path", "label", "modality", "audio_available"]]
b_rows = [["video_id", "video_path", "label", "modality", "audio_available"]]

video_counter = 0

# ===================== DATASET A =====================
print("Processing Dataset A (Video-only)...")

A_LABEL_MAP = {
    "DFD_manipulated_sequence": 1,  # Fake
    "DFD_original_sequence": 0      # Real
}

for category, label in A_LABEL_MAP.items():
    category_path = os.path.join(DATASET_A_SRC, category)

    for root, _, files in os.walk(category_path):
        for file in files:
            if file.lower().endswith((".mp4", ".avi", ".mov", ".mkv")):
                video_counter += 1
                src = os.path.join(root, file)
                dst = os.path.join(A_VIDEO_DIR, file)

                shutil.copy2(src, dst)

                a_rows.append([
                    f"A_{video_counter}",
                    f"videos/{file}",
                    label,
                    "video_only",
                    0
                ])

print(f"Dataset A videos processed: {len(a_rows)-1}")

# ===================== DATASET B =====================
print("Processing Dataset B (Audio-Visual)...")

B_LABEL_MAP = {
    "FakeVideo-FakeAudio": 1,
    "FakeVideo-RealAudio": 1,
    "RealVideo-FakeAudio": 0,
    "RealVideo-RealAudio": 0
}

for category, label in B_LABEL_MAP.items():
    category_path = os.path.join(DATASET_B_SRC, category)

    for root, _, files in os.walk(category_path):
        for file in files:
            if file.lower().endswith((".mp4", ".avi", ".mov", ".mkv")):
                video_counter += 1
                src = os.path.join(root, file)
                dst = os.path.join(B_VIDEO_DIR, file)

                shutil.copy2(src, dst)

                b_rows.append([
                    f"B_{video_counter}",
                    f"videos/{file}",
                    label,
                    "audio_visual",
                    1
                ])

print(f"Dataset B videos processed: {len(b_rows)-1}")

# ===================== WRITE CSV FILES =====================
with open(A_CSV, "w", newline="") as f:
    csv.writer(f).writerows(a_rows)

with open(B_CSV, "w", newline="") as f:
    csv.writer(f).writerows(b_rows)

print("✅ Dataset segregation completed successfully.")

import os
import csv
import shutil

# ===================== CONFIG =====================
BASE_PATH = "/content/drive/MyDrive"

DFD_MANIPULATED_PATH = os.path.join(
    BASE_PATH,
    "/content/drive/MyDrive/Major_Project/Input_Dataset/Datasets_Deepfake/DFD_manipulated_sequences/DFD_manipulated_sequences"
)

DFD_ORIGINAL_PATH = os.path.join(
    BASE_PATH,
    "/content/drive/MyDrive/Major_Project/Input_Dataset/Datasets_Deepfake/DFD_original sequences"
)

OUTPUT_BASE = os.path.join(
    BASE_PATH,
    "/content/drive/MyDrive/Major_Project/Segmented_Dataset/Dataset_A_video_only"
)

A_VIDEO_DIR = os.path.join(
    OUTPUT_BASE,
    "Dataset_A_video_only",
    "videos"
)

os.makedirs(A_VIDEO_DIR, exist_ok=True)

A_CSV = os.path.join(
    OUTPUT_BASE,
    "Dataset_A_video_only",
    "dataset_A_index.csv"
)

# ===================== CSV HEADER =====================
a_rows = [["video_id", "video_path", "label", "modality", "audio_available"]]

video_counter = 0

# ===================== PROCESS MANIPULATED (FAKE) =====================
print("Processing manipulated (fake) videos...")

for root, _, files in os.walk(DFD_MANIPULATED_PATH):
    for file in files:
        if file.lower().endswith((".mp4", ".avi", ".mov", ".mkv")):
            video_counter += 1

            src = os.path.join(root, file)
            dst_name = f"A_{video_counter}_{file}"
            dst = os.path.join(A_VIDEO_DIR, dst_name)

            shutil.copy2(src, dst)

            a_rows.append([
                f"A_{video_counter}",
                f"videos/{dst_name}",
                1,              # Fake
                "video_only",
                0
            ])

# ===================== PROCESS ORIGINAL (REAL) =====================
print("Processing original (real) videos...")

for root, _, files in os.walk(DFD_ORIGINAL_PATH):
    for file in files:
        if file.lower().endswith((".mp4", ".avi", ".mov", ".mkv")):
            video_counter += 1

            src = os.path.join(root, file)
            dst_name = f"A_{video_counter}_{file}"
            dst = os.path.join(A_VIDEO_DIR, dst_name)

            shutil.copy2(src, dst)

            a_rows.append([
                f"A_{video_counter}",
                f"videos/{dst_name}",
                0,              # Real
                "video_only",
                0
            ])

print(f"Total Dataset A videos processed: {len(a_rows) - 1}")

# ===================== WRITE CSV =====================
os.makedirs(os.path.dirname(A_CSV), exist_ok=True)

with open(A_CSV, "w", newline="") as f:
    csv.writer(f).writerows(a_rows)

print("✅ Dataset A segregation completed successfully.")

print("Manipulated path exists:", os.path.exists(DFD_MANIPULATED_PATH))
print("Original path exists:", os.path.exists(DFD_ORIGINAL_PATH))

print("\n--- Checking manipulated files ---")
for root, dirs, files in os.walk(DFD_MANIPULATED_PATH):
    print("DIR:", root)
    print("FILES:", files[:5])
    break

print("\n--- Checking original files ---")
for root, dirs, files in os.walk(DFD_ORIGINAL_PATH):
    print("DIR:", root)
    print("FILES:", files[:5])
    break

VIDEO_EXTS = (".mp4", ".avi", ".mov", ".mkv", ".webm", ".m4v")

def process_folder(src_path, label):
    global video_counter
    count = 0

    for root, _, files in os.walk(src_path):
        for file in files:
            if file.lower().endswith(VIDEO_EXTS):
                video_counter += 1
                count += 1

                src = os.path.join(root, file)
                dst_name = f"A_{video_counter}_{file}"
                dst = os.path.join(A_VIDEO_DIR, dst_name)

                shutil.copy2(src, dst)

                a_rows.append([
                    f"A_{video_counter}",
                    f"videos/{dst_name}",
                    label,
                    "video_only",
                    0
                ])

    return count
fake_count = process_folder(DFD_MANIPULATED_PATH, 1)
real_count = process_folder(DFD_ORIGINAL_PATH, 0)

print(f"Fake videos found: {fake_count}")
print(f"Real videos found: {real_count}")

"""Standardizing Dataset"""

import os
import cv2
import subprocess
from tqdm import tqdm
# ===================== BASE PATH =====================
BASE_PATH = "/content/drive/MyDrive/Major_Project"

# Segmented datasets (input)
DATASET_A_SRC = os.path.join(
    BASE_PATH,
    "/content/drive/MyDrive/Major_Project/Segmented_Dataset/Dataset_A_video_only"
)

DATASET_B_SRC = os.path.join(
    BASE_PATH,
    "/content/drive/MyDrive/Major_Project/Segmented_Dataset/Dataset_B_audio_visual"
)

# Preprocessed output base
PREPROCESS_BASE = os.path.join(
    BASE_PATH,
    "/content/drive/MyDrive/Major_Project/Pre-Processed_dataset"
)

# Standardized video folders
STD_A_DIR = os.path.join(PREPROCESS_BASE, "standardized_videos/Dataset_A")
STD_B_DIR = os.path.join(PREPROCESS_BASE, "standardized_videos/Dataset_B")

# Frame output folders
FRAMES_A_DIR = os.path.join(PREPROCESS_BASE, "frames/Dataset_A")
FRAMES_B_DIR = os.path.join(PREPROCESS_BASE, "frames/Dataset_B")

# Create folders
os.makedirs(STD_A_DIR, exist_ok=True)
os.makedirs(STD_B_DIR, exist_ok=True)
os.makedirs(FRAMES_A_DIR, exist_ok=True)
os.makedirs(FRAMES_B_DIR, exist_ok=True)

#===========================Video Standardize===================================

def standardize_video(input_video, output_video, fps=25):
    """
    Standardize FPS and codec WITHOUT resizing or clarity loss
    """
    cmd = [
        "ffmpeg", "-y",
        "-i", input_video,
        "-vsync", "cfr",
        "-r", str(fps),
        "-c:v", "libx264",
        "-preset", "slow",
        "-crf", "18",          # visually lossless
        "-pix_fmt", "yuv420p",
        output_video
    ]
    subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

#===========================Frame Extraction====================================

def extract_frames(video_path, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    cap = cv2.VideoCapture(video_path)

    frame_idx = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame_name = f"frame_{frame_idx:04d}.jpg"
        cv2.imwrite(os.path.join(output_dir, frame_name), frame)
        frame_idx += 1

    cap.release()

#===========================Standadize to extraction Frame======================

VIDEO_EXTS = (".mp4", ".avi", ".mov", ".mkv", ".webm", ".m4v")

def process_dataset(src_dir, std_dir, frames_dir):
    for file in tqdm(os.listdir(src_dir)):
        if file.lower().endswith(VIDEO_EXTS):
            video_id = os.path.splitext(file)[0].replace(" ", "_")

            src_video = os.path.join(src_dir, file)
            std_video = os.path.join(std_dir, f"{video_id}.mp4")
            frame_out = os.path.join(frames_dir, video_id)

            # Step 1: Standardize
            standardize_video(src_video, std_video)

            # Step 2: Extract frames
            extract_frames(std_video, frame_out)

#============================Main===============================================

print("🔹 Processing Dataset A (Video-only)...")
process_dataset(DATASET_A_SRC, STD_A_DIR, FRAMES_A_DIR)

print("🔹 Processing Dataset B (Audio-Visual)...")
process_dataset(DATASET_B_SRC, STD_B_DIR, FRAMES_B_DIR)

print("✅ Standardization + Frame Extraction Completed Successfully")

processed = len([
    d for d in os.listdir(FRAMES_B_DIR)
    if os.path.isdir(os.path.join(FRAMES_B_DIR, d))
])

print(f"Already processed videos: {processed}/{len(os.listdir(DATASET_B_SRC))}")

std_count = len([
    f for f in os.listdir(STD_B_DIR)
    if f.endswith(".mp4")
])

print(f"Standardized videos saved: {std_count}")

import os
import cv2
import subprocess
from tqdm import tqdm

# ===================== BASE PATH =====================
BASE_PATH = "/content/drive/MyDrive/Major_Project"

# ===================== INPUT =====================
DATASET_B_SRC = os.path.join(
    BASE_PATH,
    "Segmented_Dataset",
    "Dataset_B_audio_visual",
    "videos"
)

# ===================== OUTPUT =====================
PREPROCESS_BASE = os.path.join(BASE_PATH, "Preprocessed_Data")

STD_B_DIR = os.path.join(PREPROCESS_BASE, "standardized_videos", "Dataset_B")
FRAMES_B_DIR = os.path.join(PREPROCESS_BASE, "frames", "Dataset_B")

os.makedirs(STD_B_DIR, exist_ok=True)
os.makedirs(FRAMES_B_DIR, exist_ok=True)

VIDEO_EXTS = (".mp4", ".avi", ".mov", ".mkv", ".webm", ".m4v")

# ===================== STANDARDIZATION =====================
def standardize_video_cpu(input_video, output_video, fps=25):
    cmd = [
        "ffmpeg", "-y",
        "-i", input_video,
        "-vsync", "cfr",
        "-r", str(fps),
        "-c:v", "libx264",
        "-preset", "fast",
        "-crf", "18",
        "-pix_fmt", "yuv420p",
        output_video
    ]

    subprocess.run(
        cmd,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

# ===================== FRAME EXTRACTION =====================
def extract_frames(video_path, output_dir):
    os.makedirs(output_dir, exist_ok=True)
    cap = cv2.VideoCapture(video_path)

    idx = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break

        cv2.imwrite(
            os.path.join(output_dir, f"frame_{idx:04d}.jpg"),
            frame
        )
        idx += 1
        if idx % 5 != 0:
            idx += 1
            continue

    cap.release()

# ===================== MAIN PIPELINE =====================
def process_dataset_b_strict_skip():
    videos = [
        f for f in os.listdir(DATASET_B_SRC)
        if f.lower().endswith(VIDEO_EXTS)
    ]

    print(f"[Dataset B] Total videos found: {len(videos)}")

    skipped = 0
    processed = 0

    for file in tqdm(videos, desc="Processing Dataset B (STRICT SKIP)"):
        video_id = os.path.splitext(file)[0].replace(" ", "_")

        src_video = os.path.join(DATASET_B_SRC, file)
        std_video = os.path.join(STD_B_DIR, f"{video_id}.mp4")
        frame_out = os.path.join(FRAMES_B_DIR, video_id)

        # 🚫 STRICT SKIP CONDITION
        if (
            os.path.exists(std_video) or
            (os.path.exists(frame_out) and len(os.listdir(frame_out)) > 0)
        ):
            skipped += 1
            continue

        # ✅ Process ONLY fully unprocessed videos
        standardize_video_cpu(src_video, std_video)
        extract_frames(std_video, frame_out)

        processed += 1

    print("===================================")
    print(f"Skipped (already preprocessed): {skipped}")
    print(f"Newly processed videos: {processed}")
    print("✅ STRICT preprocessing completed")
    print("===================================")

# ===================== RUN =====================
process_dataset_b_strict_skip()

from google.colab import drive
drive.mount('/content/drive')

"""Dataset A Frame Extraction"""

import os
import cv2
from tqdm import tqdm

# ===================== BASE PATH =====================
BASE_PATH = "/content/drive/MyDrive/Major_Project"

# ===================== INPUT (DATASET A) =====================
DATASET_A_SRC = os.path.join(
    BASE_PATH,
    "Segmented_Dataset",
    "Dataset_A_video_only",
    "videos"
)

# ===================== OUTPUT =====================
OUT_BASE = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_A"
)

FRAMES_DIR = os.path.join(OUT_BASE, "frames")
os.makedirs(FRAMES_DIR, exist_ok=True)

# ===================== MANIFEST FILE =====================
MANIFEST_FILE = os.path.join(OUT_BASE, "processed_dataset_A.txt")

# Ensure manifest exists
if not os.path.exists(MANIFEST_FILE):
    open(MANIFEST_FILE, "w").close()

# Load processed videos
with open(MANIFEST_FILE, "r") as f:
    PROCESSED_SET = set(line.strip() for line in f if line.strip())

# ===================== FRAME EXTRACTION =====================
def extract_frames_rppg(video_path, out_dir, frame_stride=2):

    MAX_FRAMES = 200

    os.makedirs(out_dir, exist_ok=True)

    cap = cv2.VideoCapture(video_path)
    idx = 0
    saved = 0

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        if idx % frame_stride == 0:
            cv2.imwrite(
                os.path.join(out_dir, f"frame_{saved:04d}.png"),
                frame
            )
            saved += 1
            if saved >= MAX_FRAMES:
                break
        idx += 1

    cap.release()

# ===================== RUN =====================
VIDEO_EXTS = (".mp4", ".avi", ".mov", ".mkv", ".webm", ".m4v")

videos = [
    f for f in os.listdir(DATASET_A_SRC)
    if f.lower().endswith(VIDEO_EXTS)
]

print(f"[Dataset A] Total videos: {len(videos)}")
print(f"[Manifest] Already processed: {len(PROCESSED_SET)}")

for file in tqdm(videos, desc="Extracting frames (Dataset A | MANIFEST MODE)"):
    video_id = os.path.splitext(file)[0].replace(" ", "_")

    # 🔒 Manifest-based skip (authoritative)
    if video_id in PROCESSED_SET:
        continue

    src_video = os.path.join(DATASET_A_SRC, file)
    out_dir = os.path.join(FRAMES_DIR, video_id)

    # Process
    extract_frames_rppg(
        src_video,
        out_dir,
        frame_stride= 15   # ⭐ rPPG-safe
    )

    # ✅ Mark as completed ONLY after success
    with open(MANIFEST_FILE, "a") as f:
        f.write(video_id + "\n")

    PROCESSED_SET.add(video_id)

print("✅ Dataset A frame extraction completed (manifest-resumable, rPPG-ready)")

"""Face Alignment"""

# ===================== INSTALL (RUN ONCE) =====================
!pip install mediapipe opencv-python

# ===================== IMPORTS =====================
import os
import cv2
import mediapipe as mp
import numpy as np
from tqdm import tqdm

# ===================== BASE PATH =====================
BASE_PATH = "/content/drive/MyDrive/Major_Project"

# ===================== INPUT FRAMES (DATASET B) =====================
FRAMES_DIR = os.path.join(
    BASE_PATH, "Preprocessed_Data", "Dataset_B", "frames"
)

# ===================== OUTPUT =====================
ALIGNED_DIR = os.path.join(
    BASE_PATH, "Preprocessed_Data", "Dataset_B", "aligned_faces"
)

LOG_DIR = os.path.join(
    BASE_PATH, "Preprocessed_Data", "logs"
)

os.makedirs(ALIGNED_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

PROCESSED_LOG = os.path.join(LOG_DIR, "processed_videos.txt")
FAILED_LOG = os.path.join(LOG_DIR, "failed_videos.txt")

# ===================== LOAD LOGS (RESUME SUPPORT) =====================
def load_log(path):
    if not os.path.exists(path):
        return set()
    with open(path, "r") as f:
        return set(line.strip() for line in f.readlines())

processed_videos = load_log(PROCESSED_LOG)
failed_videos = load_log(FAILED_LOG)

# ===================== MEDIAPIPE FACE MESH =====================
mp_face = mp.solutions.face_mesh
face_mesh = mp_face.FaceMesh(
    static_image_mode=False,        # 🔥 TRACKING MODE (better for Dataset B)
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

# ===================== FACE ALIGNMENT FUNCTION =====================
def align_and_crop_face(image, landmarks, output_size=224):
    h, w, _ = image.shape

    # Eye landmarks
    left_eye = landmarks[33]
    right_eye = landmarks[263]

    left_eye = np.array([left_eye.x * w, left_eye.y * h])
    right_eye = np.array([right_eye.x * w, right_eye.y * h])

    # Compute rotation angle
    dy = right_eye[1] - left_eye[1]
    dx = right_eye[0] - left_eye[0]
    angle = np.degrees(np.arctan2(dy, dx))

    # Rotate image
    center = tuple(((left_eye + right_eye) / 2).astype(int))
    M = cv2.getRotationMatrix2D(center, angle, 1.0)
    rotated = cv2.warpAffine(image, M, (w, h))

    # Bounding box from landmarks
    xs = np.array([lm.x * w for lm in landmarks])
    ys = np.array([lm.y * h for lm in landmarks])

    x1, x2 = int(xs.min()), int(xs.max())
    y1, y2 = int(ys.min()), int(ys.max())

    # 🔥 ADD PADDING (prevents lip/mouth clipping)
    pad = int(0.15 * (x2 - x1))
    x1 = max(0, x1 - pad)
    y1 = max(0, y1 - pad)
    x2 = min(w, x2 + pad)
    y2 = min(h, y2 + pad)

    face = rotated[y1:y2, x1:x2]
    if face.size == 0:
        return None

    return cv2.resize(face, (output_size, output_size))

# ===================== MAIN PROCESS =====================
videos = sorted(os.listdir(FRAMES_DIR))
total_videos = len(videos)

processed_count = 0
failed_count = 0

with tqdm(total=total_videos, desc="Face detection & alignment", unit="video") as pbar:
    for vid in videos:
        if vid in processed_videos:
            pbar.update(1)
            continue

        in_dir = os.path.join(FRAMES_DIR, vid)
        out_dir = os.path.join(ALIGNED_DIR, vid)
        os.makedirs(out_dir, exist_ok=True)

        frame_files = sorted(
            [f for f in os.listdir(in_dir) if f.endswith((".jpg", ".png"))]
        )

        success = False

        for f in frame_files:
            in_path = os.path.join(in_dir, f)
            out_path = os.path.join(out_dir, f.replace("frame", "face"))

            if os.path.exists(out_path):
                success = True
                continue

            img = cv2.imread(in_path)
            if img is None:
                continue

            rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            results = face_mesh.process(rgb)

            if not results.multi_face_landmarks:
                continue

            landmarks = results.multi_face_landmarks[0].landmark
            face = align_and_crop_face(img, landmarks)

            if face is None:
                continue

            cv2.imwrite(out_path, face)
            success = True

        # ===================== LOGGING =====================
        if success:
            with open(PROCESSED_LOG, "a") as f:
                f.write(vid + "\n")
            processed_videos.add(vid)
            processed_count += 1
        else:
            with open(FAILED_LOG, "a") as f:
                f.write(vid + "\n")
            failed_videos.add(vid)
            failed_count += 1

        pbar.update(1)
        pbar.set_postfix(
            processed=processed_count,
            failed=failed_count
        )

print("===================================")
print("✅ Face detection & alignment DONE")
print(f"Processed videos : {processed_count}")
print(f"Failed videos    : {failed_count}")
print("Logs saved at    :", LOG_DIR)
print("===================================")

!pip uninstall -y mediapipe

!pip install mediapipe==0.10.15

import mediapipe as mp
print("MediaPipe version:", mp.__version__)
print("Has solutions:", hasattr(mp, "solutions"))

!pip install mediapipe opencv-python

import os
import cv2
import mediapipe as mp
import numpy as np
from tqdm import tqdm

BASE_PATH = "/content/drive/MyDrive/Major_Project"

FRAMES_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_B",
    "frames"
)

ALIGNED_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_B",
    "aligned_faces"
)

os.makedirs(ALIGNED_DIR, exist_ok=True)

!pip uninstall -y mediapipe
!pip install mediapipe==0.10.15

import mediapipe as mp

print("MediaPipe version:", mp.__version__)
print("Has solutions:", hasattr(mp, "solutions"))
print("mp.solutions.face_mesh exists:",
      hasattr(mp.solutions, "face_mesh") if hasattr(mp, "solutions") else False)

import mediapipe as mp

mp_face_mesh = mp.solutions.face_mesh

face_mesh = mp_face_mesh.FaceMesh(
    static_image_mode=False,
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

import os
import cv2
import numpy as np
import mediapipe as mp
from tqdm import tqdm

# ===================== PATHS =====================
BASE_PATH = "/content/drive/MyDrive/Major_Project"

FRAMES_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_B",
    "frames"
)

ALIGNED_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_B",
    "aligned_faces"
)

LOG_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "logs"
)

os.makedirs(ALIGNED_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

PROCESSED_LOG = os.path.join(LOG_DIR, "processed_videos.txt")
FAILED_LOG = os.path.join(LOG_DIR, "failed_videos.txt")

# ===================== LOAD LOGS (RESUME SUPPORT) =====================
def load_log(path):
    if not os.path.exists(path):
        return set()
    with open(path, "r") as f:
        return set(line.strip() for line in f.readlines())

processed_videos = load_log(PROCESSED_LOG)
failed_videos = load_log(FAILED_LOG)

# ===================== MEDIAPIPE =====================
mp_face_mesh = mp.solutions.face_mesh

face_mesh = mp_face_mesh.FaceMesh(
    static_image_mode=False,      # tracking mode (best for videos)
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5
)

# ===================== FACE ALIGNMENT FUNCTION =====================
def align_and_crop_face(image, landmarks, output_size=224):
    h, w, _ = image.shape

    left_eye = landmarks[33]
    right_eye = landmarks[263]

    left_eye = np.array([left_eye.x * w, left_eye.y * h], dtype=np.float32)
    right_eye = np.array([right_eye.x * w, right_eye.y * h], dtype=np.float32)

    dy = right_eye[1] - left_eye[1]
    dx = right_eye[0] - left_eye[0]
    angle = np.degrees(np.arctan2(dy, dx))

    cx = int((left_eye[0] + right_eye[0]) / 2)
    cy = int((left_eye[1] + right_eye[1]) / 2)

    M = cv2.getRotationMatrix2D((cx, cy), angle, 1.0)
    rotated = cv2.warpAffine(image, M, (w, h))

    xs = np.array([lm.x * w for lm in landmarks])
    ys = np.array([lm.y * h for lm in landmarks])

    x1, x2 = int(xs.min()), int(xs.max())
    y1, y2 = int(ys.min()), int(ys.max())

    pad = int(0.15 * (x2 - x1))
    x1 = max(0, x1 - pad)
    y1 = max(0, y1 - pad)
    x2 = min(w, x2 + pad)
    y2 = min(h, y2 + pad)

    face = rotated[y1:y2, x1:x2]
    if face.size == 0:
        return None

    return cv2.resize(face, (output_size, output_size))

# ===================== MAIN LOOP =====================
videos = sorted(os.listdir(FRAMES_DIR))
print(f"Total videos found: {len(videos)}")
print(f"Already processed : {len(processed_videos)}")

for vid in tqdm(videos, desc="Face alignment"):
    if vid in processed_videos:
        continue  # ✅ resume-safe skip

    in_dir = os.path.join(FRAMES_DIR, vid)
    out_dir = os.path.join(ALIGNED_DIR, vid)
    os.makedirs(out_dir, exist_ok=True)

    frame_files = sorted([
        f for f in os.listdir(in_dir)
        if f.lower().endswith((".jpg", ".png"))
    ])

    success = False

    for f in frame_files:
        in_path = os.path.join(in_dir, f)
        out_path = os.path.join(out_dir, f.replace("frame", "face"))

        if os.path.exists(out_path):
            success = True
            continue

        img = cv2.imread(in_path)
        if img is None:
            continue

        rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        results = face_mesh.process(rgb)

        if not results.multi_face_landmarks:
            continue

        landmarks = results.multi_face_landmarks[0].landmark
        face = align_and_crop_face(img, landmarks)

        if face is not None:
            cv2.imwrite(out_path, face)
            success = True

    # ===================== LOGGING =====================
    if success:
        with open(PROCESSED_LOG, "a") as f:
            f.write(vid + "\n")
        processed_videos.add(vid)
    else:
        with open(FAILED_LOG, "a") as f:
            f.write(vid + "\n")
        failed_videos.add(vid)

print("===================================")
print("✅ Face detection & alignment DONE")
print(f"Processed videos : {len(processed_videos)}")
print(f"Failed videos    : {len(failed_videos)}")
print("Logs saved at    :", LOG_DIR)
print("===================================")

"""**Audio Extraction**



"""

import os
import subprocess
from tqdm import tqdm

# ===================== PATHS =====================
BASE_PATH = "/content/drive/MyDrive/Major_Project"

STD_VIDEO_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "standardized_videos",
    "Dataset_B"
)

AUDIO_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_B",
    "audio"
)

LOG_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "logs"
)

os.makedirs(AUDIO_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

PROCESSED_LOG = os.path.join(LOG_DIR, "audio_processed.txt")
FAILED_LOG = os.path.join(LOG_DIR, "audio_failed.txt")

# ===================== LOAD LOGS =====================
def load_log(path):
    if not os.path.exists(path):
        return set()
    with open(path, "r") as f:
        return set(line.strip() for line in f.readlines())

processed_videos = load_log(PROCESSED_LOG)
failed_videos = load_log(FAILED_LOG)

# ===================== AUDIO EXTRACTION =====================
def extract_audio(video_path, audio_path):
    """
    Extract mono 16kHz WAV audio using FFmpeg
    """
    cmd = [
        "ffmpeg", "-y",
        "-i", video_path,
        "-ac", "1",
        "-ar", "16000",
        "-vn",
        audio_path
    ]

    result = subprocess.run(
        cmd,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL
    )

    return result.returncode == 0

# ===================== MAIN LOOP =====================
videos = sorted([
    f for f in os.listdir(STD_VIDEO_DIR)
    if f.lower().endswith((".mp4", ".avi", ".mov", ".mkv"))
])

print(f"Total standardized videos found: {len(videos)}")
print(f"Already processed audio files  : {len(processed_videos)}")

for vid in tqdm(videos, desc="Extracting audio"):
    video_id = os.path.splitext(vid)[0]

    if video_id in processed_videos:
        continue  # resume-safe skip

    video_path = os.path.join(STD_VIDEO_DIR, vid)
    audio_path = os.path.join(AUDIO_DIR, f"{video_id}.wav")

    success = extract_audio(video_path, audio_path)

    if success and os.path.exists(audio_path):
        with open(PROCESSED_LOG, "a") as f:
            f.write(video_id + "\n")
        processed_videos.add(video_id)
    else:
        with open(FAILED_LOG, "a") as f:
            f.write(video_id + "\n")
        failed_videos.add(video_id)

print("===================================")
print("✅ Audio extraction completed")
print(f"Processed audio files : {len(processed_videos)}")
print(f"Failed audio files    : {len(failed_videos)}")
print("Logs saved at         :", LOG_DIR)
print("===================================")

"""Dataset A Face Alignment"""

!pip uninstall -y mediapipe
!pip install mediapipe==0.10.15

import os
import cv2
import numpy as np
import mediapipe as mp
from tqdm import tqdm

# ===================== PATHS =====================
BASE_PATH = "/content/drive/MyDrive/Major_Project"

FRAMES_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_A",
    "frames"
)

ALIGNED_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_A",
    "aligned_faces"
)

LOG_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "logs"
)

os.makedirs(ALIGNED_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

PROCESSED_LOG = os.path.join(LOG_DIR, "A_processed_videos.txt")
FAILED_LOG = os.path.join(LOG_DIR, "A_failed_videos.txt")

# ===================== LOAD LOGS =====================
def load_log(path):
    if not os.path.exists(path):
        return set()
    with open(path, "r") as f:
        return set(line.strip() for line in f.readlines())

processed_videos = load_log(PROCESSED_LOG)
failed_videos = load_log(FAILED_LOG)

# ===================== MEDIAPIPE FACE MESH =====================
mp_face_mesh = mp.solutions.face_mesh

face_mesh = mp_face_mesh.FaceMesh(
    static_image_mode=True,   # 🔥 per-frame precision (better for rPPG)
    max_num_faces=1,
    refine_landmarks=True,
    min_detection_confidence=0.6
)

# ===================== ALIGNMENT FUNCTION (NO RESIZE) =====================
def align_and_crop_face_rppg(image, landmarks):
    h, w, _ = image.shape

    # Eye landmarks
    left_eye = landmarks[33]
    right_eye = landmarks[263]

    left_eye = np.array([left_eye.x * w, left_eye.y * h], dtype=np.float32)
    right_eye = np.array([right_eye.x * w, right_eye.y * h], dtype=np.float32)

    # Compute rotation angle
    dy = right_eye[1] - left_eye[1]
    dx = right_eye[0] - left_eye[0]
    angle = np.degrees(np.arctan2(dy, dx))

    # Rotation center
    cx = int((left_eye[0] + right_eye[0]) / 2)
    cy = int((left_eye[1] + right_eye[1]) / 2)

    M = cv2.getRotationMatrix2D((cx, cy), angle, 1.0)
    rotated = cv2.warpAffine(image, M, (w, h))

    # Landmark bounding box
    xs = np.array([lm.x * w for lm in landmarks])
    ys = np.array([lm.y * h for lm in landmarks])

    x1, x2 = int(xs.min()), int(xs.max())
    y1, y2 = int(ys.min()), int(ys.max())

    # Small padding (10%) – conservative for rPPG
    pad = int(0.10 * (x2 - x1))
    x1 = max(0, x1 - pad)
    y1 = max(0, y1 - pad)
    x2 = min(w, x2 + pad)
    y2 = min(h, y2 + pad)

    face = rotated[y1:y2, x1:x2]
    if face.size == 0:
        return None

    return face   # 🔥 NO RESIZE

# ===================== MAIN LOOP =====================
videos = sorted(os.listdir(FRAMES_DIR))

print(f"[Dataset A] Total videos found: {len(videos)}")
print(f"[Dataset A] Already processed : {len(processed_videos)}")

for vid in tqdm(videos, desc="Dataset A Face Alignment"):
    if vid in processed_videos:
        continue  # resume-safe

    in_dir = os.path.join(FRAMES_DIR, vid)
    out_dir = os.path.join(ALIGNED_DIR, vid)
    os.makedirs(out_dir, exist_ok=True)

    frame_files = sorted([
        f for f in os.listdir(in_dir)
        if f.lower().endswith((".jpg", ".png"))
    ])

    success = False

    for f in frame_files:
        in_path = os.path.join(in_dir, f)
        out_path = os.path.join(out_dir, f.replace("frame", "face"))

        if os.path.exists(out_path):
            success = True
            continue

        img = cv2.imread(in_path)
        if img is None:
            continue

        rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        results = face_mesh.process(rgb)

        if not results.multi_face_landmarks:
            continue

        landmarks = results.multi_face_landmarks[0].landmark
        face = align_and_crop_face_rppg(img, landmarks)

        if face is not None:
            cv2.imwrite(out_path, face)
            success = True

    # ===================== LOGGING =====================
    if success:
        with open(PROCESSED_LOG, "a") as f:
            f.write(vid + "\n")
        processed_videos.add(vid)
    else:
        with open(FAILED_LOG, "a") as f:
            f.write(vid + "\n")
        failed_videos.add(vid)

print("===================================")
print("✅ Dataset A face alignment DONE")
print(f"Processed videos : {len(processed_videos)}")
print(f"Failed videos    : {len(failed_videos)}")
print("Logs saved at    :", LOG_DIR)
print("===================================")

"""Meta"""

import os
import csv
import wave
from tqdm import tqdm

# ===================== CONFIG =====================
BASE_PATH = "/content/drive/MyDrive/Major_Project"

FPS = 25
FRAME_TOLERANCE = 5

# ===================== PATHS =====================
FACES_BASE = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_B",
    "Aligned_faces"
)

AUDIO_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_B",
    "audio"
)

META_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "metadata"
)

LOG_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "logs"
)

os.makedirs(META_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

META_CSV = os.path.join(META_DIR, "dataset_B_metadata_3parts.csv")
VALID_LOG = os.path.join(LOG_DIR, "B_valid_videos.txt")
INVALID_LOG = os.path.join(LOG_DIR, "B_invalid_videos.txt")

# ===================== HELPERS =====================
def get_audio_duration(wav_path):
    with wave.open(wav_path, "r") as wf:
        return wf.getnframes() / float(wf.getframerate())

def count_frames(folder):
    if not os.path.exists(folder):
        return 0
    return len([
        f for f in os.listdir(folder)
        if f.lower().endswith((".jpg", ".png"))
    ])

def load_log(path):
    if not os.path.exists(path):
        return set()
    with open(path, "r") as f:
        return set(line.strip() for line in f.readlines())

valid_done = load_log(VALID_LOG)
invalid_done = load_log(INVALID_LOG)

# ===================== CSV SETUP =====================
write_header = not os.path.exists(META_CSV)
csv_file = open(META_CSV, "a", newline="")
writer = csv.writer(csv_file)

if write_header:
    writer.writerow([
        "video_id",
        "dataset",
        "label",
        "fps",
        "num_frames",
        "audio_duration_sec",
        "expected_frames",
        "frame_diff",
        "av_sync_status",
        "faces_part1_path",
        "faces_part2_path",
        "faces_part3_path",
        "audio_path"
    ])

# ===================== MAIN LOOP =====================
videos = sorted(os.listdir(FACES_BASE))
print(f"[Dataset B] Videos found: {len(videos)}")

for vid in tqdm(videos, desc="AV Sync + Metadata (3 parts)"):
    if vid in valid_done or vid in invalid_done:
        continue

    part1 = os.path.join(FACES_BASE, "aligned_faces_1")
    part2 = os.path.join(FACES_BASE, "aligned_faces_2")
    part3 = os.path.join(FACES_BASE, "aligned_faces_3")
    audio_path = os.path.join(AUDIO_DIR, f"{vid}.wav")

    # Basic existence check
    if not (os.path.exists(part1) and os.path.exists(part2) and os.path.exists(part3)):
        with open(INVALID_LOG, "a") as f:
            f.write(vid + "\n")
        continue

    if not os.path.exists(audio_path):
        with open(INVALID_LOG, "a") as f:
            f.write(vid + "\n")
        continue

    # Use part_1 for frame count reference
    num_frames = count_frames(part1)
    audio_duration = get_audio_duration(audio_path)
    expected_frames = int(audio_duration * FPS)
    frame_diff = abs(num_frames - expected_frames)

    if frame_diff <= FRAME_TOLERANCE:
        status = "VALID"
        with open(VALID_LOG, "a") as f:
            f.write(vid + "\n")
        valid_done.add(vid)
    else:
        status = "INVALID"
        with open(INVALID_LOG, "a") as f:
            f.write(vid + "\n")
        invalid_done.add(vid)

    label = -1  # assign during training

    writer.writerow([
        vid,
        "Dataset_B",
        label,
        FPS,
        num_frames,
        round(audio_duration, 3),
        expected_frames,
        frame_diff,
        status,
        part1,
        part2,
        part3,
        audio_path
    ])

csv_file.close()

print("===================================")
print("✅ Metadata generation completed (3 face parts)")
print(f"Valid videos   : {len(valid_done)}")
print(f"Invalid videos : {len(invalid_done)}")
print("Metadata saved :", META_CSV)
print("===================================")

import os
import csv
import wave
from tqdm import tqdm

# ===================== CONFIG =====================
BASE_PATH = "/content/drive/MyDrive/Major_Project"

FPS = 25                    # MUST match video standardization
FRAME_TOLERANCE = 5         # allowable frame mismatch

FACES_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_B",
    "Aligned_faces",
    "aligned_faces_3"
)

AUDIO_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "Dataset_B",
    "audio"
)

META_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "metadata"
)

LOG_DIR = os.path.join(
    BASE_PATH,
    "Preprocessed_Data",
    "logs"
)

os.makedirs(META_DIR, exist_ok=True)
os.makedirs(LOG_DIR, exist_ok=True)

META_CSV = os.path.join(META_DIR, "dataset_B_metadata.csv")
VALID_LOG = os.path.join(LOG_DIR, "B_valid_videos.txt")
INVALID_LOG = os.path.join(LOG_DIR, "B_invalid_videos.txt")

# ===================== HELPERS =====================
def get_audio_duration(wav_path):
    with wave.open(wav_path, "r") as wf:
        frames = wf.getnframes()
        rate = wf.getframerate()
        return frames / float(rate)

def count_frames(folder):
    return len([
        f for f in os.listdir(folder)
        if f.lower().endswith((".jpg", ".png"))
    ])

# ===================== LOAD PREVIOUS LOGS =====================
def load_log(path):
    if not os.path.exists(path):
        return set()
    with open(path, "r") as f:
        return set(line.strip() for line in f.readlines())

valid_done = load_log(VALID_LOG)
invalid_done = load_log(INVALID_LOG)

# ===================== CSV HEADER =====================
write_header = not os.path.exists(META_CSV)
csv_file = open(META_CSV, "a", newline="")
writer = csv.writer(csv_file)

if write_header:
    writer.writerow([
        "video_id",
        "dataset",
        "label",
        "fps",
        "num_frames",
        "audio_duration_sec",
        "expected_frames",
        "frame_diff",
        "av_sync_status",
        "faces_path",
        "audio_path"
    ])

# ===================== MAIN LOOP =====================
videos = sorted(os.listdir(FACES_DIR))
print(f"[Dataset B] Videos found: {len(videos)}")

for vid in tqdm(videos, desc="AV Sync Validation"):
    if vid in valid_done or vid in invalid_done:
        continue  # resume-safe

    faces_path = os.path.join(FACES_DIR, vid)
    audio_path = os.path.join(AUDIO_DIR, f"{vid}.wav")

    if not os.path.exists(audio_path):
        with open(INVALID_LOG, "a") as f:
            f.write(vid + "\n")
        continue

    num_frames = count_frames(faces_path)
    audio_duration = get_audio_duration(audio_path)
    expected_frames = int(audio_duration * FPS)
    frame_diff = abs(num_frames - expected_frames)

    if frame_diff <= FRAME_TOLERANCE:
        status = "VALID"
        with open(VALID_LOG, "a") as f:
            f.write(vid + "\n")
        valid_done.add(vid)
    else:
        status = "INVALID"
        with open(INVALID_LOG, "a") as f:
            f.write(vid + "\n")
        invalid_done.add(vid)

    # ===== TEMPORARY LABEL PLACEHOLDER =====
    label = -1   # assign real/fake during training split

    writer.writerow([
        vid,
        "Dataset_B",
        label,
        FPS,
        num_frames,
        round(audio_duration, 3),
        expected_frames,
        frame_diff,
        status,
        faces_path,
        audio_path
    ])

csv_file.close()

print("===================================")
print("✅ AV sync validation completed")
print(f"Valid videos   : {len(valid_done)}")
print(f"Invalid videos : {len(invalid_done)}")
print("Metadata saved :", META_CSV)
print("===================================")
